### ISSUE TITLE
Request: Adding notes for Python

### ISSUE THREAD

**Issue by Saharsh0028** [sayakbanerjee1999/Coding-Notes#7]
Hi. I am a fresher at VIT-Vellore and I have BCSE101E in Semester 1 - we have a new syllabus where we are learning Python.
I'd like to request you to add notes and codes for Python too.

**Comment by sayakbanerjee1999** [comment]
Hey Saharsh this repository and codes are targeted to help people preparing for placements. 
For academic courses and help in Python there are a lot of materials available accross internet which you can go through.
For furthur details do not hesitate to connect with me via LinkedIn or drop an email. I will drop the links for both in the description of the repository
